web:
  restart: always
  build: ./app
  expose:
    - "5000"
  volumes:
    - .:/code
  links:
    - redis

redis:
  image: redis

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
