web:
  restart: always
  build: .:/code
  expose:
    - "5000"
  volumes:
    - .:/code

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
